### ISSUE TITLE
Data integrity with the candidate contributions

### ISSUE THREAD

**Issue by mkalish** [codefordc/dc-campaign-finance-watch#140]
Some candidates list of their own contributions and this needs to be examined

## Context
Data is not correct for Charles Allen in particular

## Expected Behavior
Charles Allen should only have candidate contributions from his own ward

## Actual Behavior
Contributions should only be from the ward Charles Allen lives in

## Possible Fix
This might be an issue with how the data was entered into the OCF site.  I would start by looking at the raw CSV and filtering everything but Charles Allen as a candidate and Candidate as the contributor type to see if this is not the expected result

## Steps to Reproduce
1.  Look at Charles Allen's campaign
2. Examine the ward concentration graph
3. Candidate contribution row includes contributions from multiple wards

## Context
The data for some candidates might not be correct

## Your Environment

* Operating System: OSX
* Browser: Chrome
* Desktop or mobile: Desktop

**Comment by jkoul** [comment]
According to the raw data, Allen contributed $726 to his campaign over 5 contributions....all from the same address. No contributions from "Individuals" had his name on them.

So the raw data isn't the issue. Hmmmmm. I wonder if there's something wrong with how we're processing it?

To make matters worse, it appears the self-contribution percentage is off. 726/155079 equals 0.468%, but Allen's page says  0.153%. So that broadens the error. We should really go through and do more verification on every parameter, not just this one.

**Comment by mkalish** [comment]
The issue stems from how we are assigning contributor type, PR is going up shortly
